baseURL = "https://gbaranski.com"
languageCode = "en-us"
title = "Grzegorz Baranski"
theme = "researcher"

disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false
googleAnalytics = "G-E2VXN66JK3"  # add your tracking id

[params]
  author = "Grzegorz Baranski"
  description = "Personal website, some information about what I work on"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "by gbaranski"
    url = "https://github.com/gbaranski/gbaranski.com"

[permalinks]
  "/" = "/:filename"
